name: recipen-pipeline

on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        
      - name: Install xvfb for headless Chrome
        run: sudo apt-get install -y xvfb

      - name: Run tests in headless mode
        env:
          CHROME_BIN: google-chrome-stable
          DISPLAY: :99
        run: |
          xvfb-run -s "-screen 0 1920x1080x24" npm test -- --watch=false --browsers=ChromeHeadless --no-progress

      - name: Build the application
        run: npm run build -- --prod

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: recipen-app
          path: dist/
